preprocess:
  seq_length: 100
  min_freq: 1
  max_freq: 1.0

data:
  train_val_test_split: !!python/tuple [0.75,  0.15, 0.1]
  batch_size: 128
  num_workers: 0
  pin_memory: true

model:
  vocab_size: null
  output_size: 1
  embedding_size: 128
  hidden_size: 256

trainer:
  learning_rate: 0.001
  num_epochs: 10
  weight: null

callback:
  checkpoint:
    enable: true
    dirpath: null
    filename: null
    weights_only: true
  earlystopping:
    enable: true
    patience: 3